import { Link } from 'react-router-dom';
import { ArrowUpRight, Asterisk } from 'lucide-react';
import { Action, Eyebrow, Reveal } from './Primitives';
import { site } from '../config/site';

export const Philosophy = () => <section className="philosophy container" id="philosophy" data-testid="philosophy"><Reveal><Eyebrow id="philosophy-label">A PRODUCT MINDSET. NOT JUST A SERVICE.</Eyebrow><h2 className="section-heading" data-testid="philosophy-heading">We don’t just<br />build software<span className="accent-text">.</span></h2><div className="philosophy-bottom"><Asterisk className="philosophy-star" strokeWidth={1} /><p data-testid="philosophy-description">We build products around <span>real problems, real people and real businesses.</span> From our own technology to ambitious ideas from our partners, we bring strategy, design and engineering together.</p></div></Reveal></section>;

export const Marquee = () => <div className="marquee" aria-label="Think deeply. Design thoughtfully. Build exceptionally." data-testid="editorial-marquee"><div className="marquee-track" aria-hidden="true">{[0, 1].map(i => <span key={i}>THINK DEEPLY <Asterisk /> DESIGN THOUGHTFULLY <Asterisk /> BUILD EXCEPTIONALLY <Asterisk /></span>)}</div></div>;

const steps = [ ['01', 'Discover', 'Ask better questions. Understand the people, the problem and the possibilities.'], ['02', 'Define & design', 'Give the idea a clear direction. Make it tangible. Test what matters.'], ['03', 'Build & refine', 'Bring design and engineering together, with care in every detail.'], ['04', 'Launch & learn', 'Put it in real hands. Listen closely. Make the next version better.'] ];
export const Process = () => <section className="process-section container" data-testid="process"><Reveal className="split-heading"><Eyebrow id="process-label">FROM THE FIRST WHAT IF</Eyebrow><h2 className="section-heading" data-testid="process-heading">A clear path.<br /><span className="muted-text">Room for possibility.</span></h2></Reveal><div className="process-grid">{steps.map(([num, title, text], i) => <Reveal delay={i * .08} className="process-step" key={num}><span className="process-number" data-testid={`process-number-${num}`}>{num}</span><h3 data-testid={`process-title-${num}`}>{title}</h3><p data-testid={`process-description-${num}`}>{text}</p></Reveal>)}</div></section>;

const principles = [['THINK', 'Find the right problem before building the solution.'], ['DESIGN', 'Turn complexity into experiences that feel natural.'], ['BUILD', 'Engineer products capable of growing beyond version one.']];
export const Principles = () => <section className="principles container" data-testid="principles"><Reveal className="principles-heading"><Eyebrow id="principles-label">THE APPETISER WAY</Eyebrow><h2 className="section-heading" data-testid="principles-heading">From idea<br />to <span className="accent-text">impact.</span></h2></Reveal><div className="principle-rows">{principles.map(([title, text], i) => <Reveal key={title} delay={i * .1} className="principle-row"><span className="small-label">0{i + 1}</span><h3 data-testid={`principle-${title.toLowerCase()}`}>{title}</h3><p data-testid={`principle-copy-${i}`}>{text}</p><ArrowUpRight size={25} /></Reveal>)}</div></section>;

export const CareersTeaser = () => <section className="careers-teaser container" data-testid="careers-teaser"><Reveal className="careers-teaser-inner"><div className="careers-teaser-copy"><Eyebrow id="careers-teaser-label">GOOD PEOPLE. GREAT POSSIBILITIES.</Eyebrow><h2 className="section-heading" data-testid="careers-teaser-heading">Your next chapter.<br /><span className="accent-text">Our next big thing.</span></h2><p data-testid="careers-teaser-copy">Care about what you create?<br />You might feel right at home here.</p><Action to="/careers" id="careers-teaser-link" variant="light" arrow="up">Build with us</Action></div><Link to="/careers" className="careers-teaser-art" data-testid="careers-teaser-visual-link" aria-label="Discover careers at Appetiser India"><img loading="lazy" src={site.builderImage} alt="Interlocking sculptural forms representing a team building together" /></Link></Reveal></section>;