import { useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { QrCode, ScanLine, ArrowRight, Smartphone, Store, ChefHat, Check, LockKeyhole, Layers } from 'lucide-react';
import { Action, Eyebrow, Reveal } from '../Primitives';
import { MenuDemo, BitByteWordmark } from './MenuDemo';

const scenes = [
  { label: 'THE FIRST HELLO', title: <>Scan.<br />Order. Enjoy.</>, copy: 'Customers can move from table to menu without waiting for a traditional ordering flow.', tab: 'Scan' },
  { label: 'THE CUSTOMER EXPERIENCE', title: <>The menu,<br />in their hands.</>, copy: 'Explore the dishes. Find a favourite. Place an order. An intuitive experience that starts right at the table.', tab: 'Browse' },
  { label: 'A SIMPLER CONNECTION', title: <>Orders move<br />where they need to.</>, copy: 'A clear journey from customer to restaurant. Less friction between choosing a dish and placing an order.', tab: 'Order' },
  { label: 'THE RESTAURANT EXPERIENCE', title: <>Operations,<br />without the chaos.</>, copy: 'A dedicated dashboard and login give restaurant teams a place to access their restaurant environment.', tab: 'Restaurant' },
];

const ScanScene = ({ onScan }) => <div className="scan-scene"><div className="table-circle" aria-hidden="true" /><div className="qr-tent"><BitByteWordmark id="scan-wordmark" /><span className="small-label">A LITTLE SCAN.<br />A LOT TO LOOK FORWARD TO.</span><div className="qr-surface"><QrCode size={126} strokeWidth={1.3} /><motion.div className="scan-beam" animate={{ top: ['5%', '90%', '5%'] }} transition={{ repeat: Infinity, duration: 4, ease: 'easeInOut' }} /></div><span className="qr-table">TABLE 07</span><button data-testid="try-menu-preview" onClick={onScan}><ScanLine size={16} />Try the menu preview<ArrowRight size={15} /></button></div><span className="floating-note"><Smartphone size={16} />Your table. Your menu.</span></div>;

const OrderScene = () => <div className="order-flow"><div className="order-flow-header"><span className="small-label">FROM A CHOICE TO AN ORDER</span><h3 data-testid="order-flow-title">A simpler way through.</h3></div>{[[Smartphone, 'Customer', 'Choose something delicious'], [Layers, 'Order system', 'Place a digital order'], [Store, 'Restaurant', 'The restaurant experience']].map(([Icon, title, text], i) => <div className="flow-step" key={title}><span className="flow-icon"><Icon size={24} /></span><div><strong data-testid={`flow-step-${i}`}>{title}</strong><p>{text}</p></div><Check size={17} /></div>)}<div className="flow-proposed"><ChefHat size={20} /><span>Kitchen hand-off<small>Proposed workflow · to be verified</small></span></div><span className="demo-note">Illustrative journey, not a live order system.</span></div>;

const RestaurantScene = () => <div className="restaurant-preview"><div className="restaurant-preview-top"><BitByteWordmark id="restaurant-wordmark" /><span><LockKeyhole size={12} />Restaurant access</span></div><div className="restaurant-preview-body"><div className="restaurant-logo-icon"><Store size={37} strokeWidth={1.4} /></div><span className="small-label">THE OTHER SIDE OF THE EXPERIENCE</span><h3 data-testid="restaurant-preview-heading">Your restaurant.<br />One place to begin.</h3><p data-testid="restaurant-preview-copy">Access your restaurant environment through BitByte’s dedicated dashboard.</p><Action variant="product" id="restaurant-access-enquiry" to="/contact?interest=BitByte%20Restro">Ask about restaurant access</Action><span className="demo-note">Illustrative view. Ask us for a walkthrough of the current product.</span></div></div>;

export const ProductStory = ({ product }) => {
  const [active, setActive] = useState(0);
  const refs = useRef([]);
  const goTo = i => { setActive(i); if (window.innerWidth >= 768) refs.current[i]?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'center' }); };
  return <section className="bitbyte-story" data-testid="bitbyte-story"><div className="container"><Reveal className="story-intro"><Eyebrow id="story-label">SMALL INTERACTIONS. A BETTER EXPERIENCE.</Eyebrow><span className="story-preview-label" data-testid="story-preview-disclaimer">An interactive illustration of the ordering journey</span></Reveal><div className="story-layout"><div className="story-scenes">{scenes.map((scene, i) => <motion.article ref={el => refs.current[i] = el} key={scene.label} className={`story-copy ${active === i ? 'is-active' : ''}`} onViewportEnter={() => setActive(i)} viewport={{ amount: .65 }} data-testid={`story-scene-${i}`}><span className="story-scene-label">0{i + 1} / {scene.label}</span><h3 data-testid={`story-heading-${i}`}>{scene.title}</h3><p data-testid={`story-copy-${i}`}>{scene.copy}</p><button className="story-see" data-testid={`story-show-${i}`} onClick={() => { setActive(i); if (window.innerWidth < 768) document.getElementById('story-visual')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); }}>Explore this moment <ArrowRight size={16} /></button></motion.article>)}</div><div className="story-sticky" id="story-visual"><div className="story-tabs" role="tablist" aria-label="BitByte journey">{scenes.map((s, i) => <button key={s.tab} data-testid={`story-tab-${i}`} role="tab" aria-selected={active === i} aria-controls="story-scene-panel" onClick={() => goTo(i)} className={active === i ? 'active' : ''}><span>0{i + 1}</span>{s.tab}</button>)}</div><div className="story-visual-panel" id="story-scene-panel" role="tabpanel" aria-label={scenes[active].tab} data-testid="story-active-panel"><motion.div className="story-panel-content" key={active} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .5 }}>{active === 0 && <ScanScene onScan={() => goTo(1)} />}{active === 1 && <MenuDemo prefix="story" />}{active === 2 && <OrderScene />}{active === 3 && <RestaurantScene />}</motion.div><span className="story-visual-footer">DESIGNED AROUND THE DINING EXPERIENCE.</span></div></div></div><Reveal className="bitbyte-cta"><span className="small-label">LESS FRICTION. MORE FLAVOUR.</span><h3 data-testid="bitbyte-cta-heading">{product.content.audience}</h3><p data-testid="bitbyte-cta-description">{product.content.cta}</p><div className="button-group"><Action to={product.websiteUrl || `/products/${product.slug}`} variant="product" id="bitbyte-cta-explore">Explore BitByte</Action><Action to="/contact?interest=BitByte%20Restro" variant="product-outline" id="bitbyte-cta-contact">Talk to us</Action></div></Reveal></div></section>;
};