import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { SEO } from '../components/Layout';
import { PageHero, Action, Eyebrow, Reveal } from '../components/Primitives';
import { CareersModel } from '../components/CareersModel';
import { jobs, departments } from '../data/jobs';
import { careersMailto } from '../config/site';

const values = [['Care about the craft', 'The details make the difference. We take pride in thoughtful decisions, well-made experiences and work that holds up.'], ['Stay curious', 'Better questions lead to better products. We keep exploring, keep learning and stay open to being wrong.'], ['Own the outcome', 'See the bigger picture. Take responsibility for the work and for the difference it makes to the people using it.'], ['Build together', 'The best ideas don’t belong to one discipline. We share early, listen generously and make each other better.']];

const OpenRoles = ({ openJobs }) => {
  const [department, setDepartment] = useState(departments.find(d => openJobs.some(j => j.department === d)) || departments[0]);
  const visible = openJobs.filter(job => job.department === department);
  return <>
    <div className="role-tabs" role="tablist" aria-label="Role categories" data-testid="role-tabs">{departments.map(d => { const count = openJobs.filter(j => j.department === d).length; return <button key={d} role="tab" aria-selected={department === d} className={department === d ? 'active' : ''} onClick={() => setDepartment(d)} data-testid={`role-tab-${d.toLowerCase()}`}>{d}<span>{count.toString().padStart(2, '0')}</span></button>; })}</div>
    <AnimatePresence mode="wait"><motion.div key={department} className="job-rows" role="tabpanel" data-testid="job-rows" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} transition={{ duration: .35, ease: [.22, 1, .36, 1] }}>
      {visible.length ? visible.map(job => <Link to={`/careers/${job.id}`} key={job.id} className="job-row" data-testid={`job-${job.id}`}><span><strong>{job.role}</strong><small>{job.description}</small></span><span>{job.duration}</span><span>{job.location}</span><span>{job.type}</span><span className="job-apply">View role <ArrowUpRight /></span></Link>) : <p className="no-roles-inline" data-testid="no-roles-in-department">No {department} openings right now — check the other category or introduce yourself below.</p>}
    </motion.div></AnimatePresence>
  </>;
};

export default function Careers() {
  const openJobs = jobs.filter(job => job.isOpen);
  return <><SEO title="Careers — Build the future" /><PageHero id="careers" eyebrow="WE’RE GROWING" lines={['Build the future,', 'not just your next role.']} description="Join a team that cares about great products, thoughtful technology and the people using what we build."><Action to="/careers#opportunities" id="careers-explore-roles" arrow="up">Explore opportunities</Action></PageHero><div className="container"><CareersModel /></div><section className="careers-philosophy container"><Reveal className="careers-philosophy-intro"><Eyebrow id="careers-philosophy-label">MAKE YOUR WORK MATTER</Eyebrow><h2 className="section-heading" data-testid="careers-philosophy-heading">Do work you’re<br /><span className="accent-text">proud to ship.</span></h2><p data-testid="careers-philosophy-copy">At Appetiser India, you’ll work on products that solve real problems — including our own technology and products we build with ambitious partners.</p></Reveal><div className="career-values">{values.map(([title, text], i) => <Reveal className="career-value" key={title}><span className="small-label">0{i + 1}</span><h3 data-testid={`career-value-${i}`}>{title}</h3><p data-testid={`career-value-copy-${i}`}>{text}</p></Reveal>)}</div></section><section className="open-roles container" id="opportunities"><Reveal><div className="roles-heading"><div><Eyebrow id="roles-label">FIND YOUR NEXT CHAPTER</Eyebrow><h2 className="section-heading" data-testid="roles-heading">Open opportunities<span className="accent-text">.</span></h2></div><span className="roles-count" data-testid="open-role-count">{openJobs.length.toString().padStart(2, '0')} OPEN ROLES</span></div>{openJobs.length ? <OpenRoles openJobs={openJobs} /> : <div className="no-roles" data-testid="no-open-roles"><span className="availability-ring" aria-hidden="true" /><div><h3>No open roles right now.</h3><p>Good conversations don’t need to wait for a job opening.<br />If our way of thinking feels like yours, we’d love to hear from you.</p></div><a href={careersMailto()} data-testid="careers-introduce-link">Introduce yourself <ArrowUpRight size={18} /></a></div>}<p className="apply-note" data-testid="apply-note">Open a role to see responsibilities, what you’ll learn and how to apply.</p></Reveal></section><section className="resume-cta container"><Reveal><Eyebrow id="resume-label">LET’S KEEP THE DOOR OPEN</Eyebrow><h2 className="section-heading" data-testid="resume-heading">Don’t see your role?</h2><p data-testid="resume-copy">We’re always interested in meeting talented people who care about building exceptional digital products.</p><Action to={careersMailto()} id="send-resume" arrow="up">Send your resume</Action><span className="resume-note" data-testid="resume-instructions">Tell us who you are, what you do and what you’d love to build.</span></Reveal><Link className="resume-about" to="/about" data-testid="careers-about-link">Get to know Appetiser <ArrowUpRight size={17} /></Link></section></>;
}